# Generated by Django 5.0.6 on 2024-07-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=100)),
                ('favo_instrument', models.CharField(choices=[('drum', 'drum'), ('pianno', 'pianno'), ('harmony', 'harmony')], max_length=10)),
            ],
        ),
    ]
